apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: foxhound-web
 name: foxhound-web
spec:
 replicas: 2
 selector:
   matchLabels:
     app: foxhound-web
 template:
   metadata:
     labels:
       app: foxhound-web
   spec:
     containers:
       - image: quay.io/akrohg/acm-demo:v1
         imagePullPolicy: Always
         name: foxhound-web
         ports:
           - containerPort: 8080
